name: "Gatsby Cache"
description: "Cache build outputs for Gatsby's Conditional Page Build."
author: "jongwooo <jongwooo.han@gmail.com>"
inputs:
  use-cache:
    description: "A boolean value to enable/disable conditional page build."
    required: false
    default: true
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the key."
runs:
  using: "node16"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
  post-if: success()
branding:
  icon: "archive"
  color: "purple"
